#ifndef CONSTAUTOPLACING_H
#define CONSTAUTOPLACING_H

constexpr short FREE_CELLS = 1;
constexpr short OCCUPIED_CELLS = 0;
constexpr short AMOUNT_GENERATED_NUMBERS_FOR_FIRST_SHIPS = 500;
constexpr short AMOUNT_GENERATED_NUMBERS_FOR_SECOND_SHIPS = 450;
constexpr short AMOUNT_GENERATED_NUMBERS_FOR_THIRD_SHIPS = 400;
constexpr short AMOUNT_GENERATED_NUMBERS_FOR_FORTH_SHIPS = 350;

#endif // CONSTAUTOPLACING_H
