#ifndef SIZES_H
#define SIZES_H

#define CHIP_SIZE 70
#define CHIP_SHIFT 25
#define CELL_WIDTH CHIP_SIZE
#define CELL_HEIGHT 420
#define DICE_SIZE 50
#define DICE_DOT_OFFSET 10
#define DICE_DOT_SIZE 5
#define DICE_DOT_L DICE_DOT_OFFSET
#define DICE_DOT_R DICE_SIZE - DICE_DOT_OFFSET
#define LEFT_BOARD_OFFSET 245
#define RIGHT_BOARD_OFFSET 335
#define TOP_CELL_OFFSET 50
#define CELL_X_SPACE 24
#define AVAILABLE_MARK_SIZE 15
#define AVAILABLE_MARK_Y_OFFSET 5
#define REMOVE_BUTTON_SIZE 100
#define REMOVE_BUTTON_CENTRE_SIZE 20

#endif // SIZES_H
