#ifndef DYNAMICLINKLIBRARY_GLOBAL_H
#define DYNAMICLINKLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DYNAMICLINKLIBRARY_LIBRARY)
#define DYNAMICLINKLIBRARY_EXPORT Q_DECL_EXPORT
#else
#define DYNAMICLINKLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // DYNAMICLINKLIBRARY_GLOBAL_H
